_target_: src.models.unet.UNetModule

use_ema: true

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0001
  weight_decay: 0.0

# optimizer:
#   _target_: torch.optim.SGD
#   _partial_: true
#   lr: 0.0001
#   weight_decay: 1e-5

# optimizer:
#   _target_: torch.optim.RMSprop
#   _partial_: true
#   lr: 0.0001
#   weight_decay: 1e-5

scheduler:
  _target_: torch.optim.lr_scheduler.ExponentialLR
  _partial_: true
  gamma: 0.95

# scheduler:
#   _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
#   _partial_: true
#   mode: min
#   factor: 0.1
#   patience: 10

net:
  _target_: src.models.unet.net.UNetAttention

  in_channels: 1 # the channel count of the input
  out_channels: 1 # the channel count of the output
  base_channels: 64 # the base channel count for the model
  block: Residual # type of blocks for each level
  n_layer_blocks: 1 # number of blocks at each level
  channel_multipliers: [1, 2, 4] # the multiplicative factors for number of channels for each level
  drop_rate: 0 # drop out layer
  attention: null # type of attentions for each level
  attention_levels: null # the levels at which attention should be performed
  n_attention_heads: null # the number of attention heads
  n_attention_layers: null # the number of attention layers

# other segmentation-loss in https://smp.readthedocs.io/en/latest/losses.html
criterion:
  # BCE Loss for binary-class or multi-label
  _target_: segmentation_models_pytorch.losses.SoftBCEWithLogitsLoss
  # smooth_factor: 0.1

  # CE Loss for multi-class
  # _target_: segmentation_models_pytorch.losses.SoftCrossEntropyLoss
  # smooth_factor: 0.1

  # Dice Loss for binary-class or multi-label or multi-class
  # _target_: segmentation_models_pytorch.losses.DiceLoss
  # mode: binary
  # smooth: 0.1

  # Focal Loss for binary-class or multi-label or multi-class
  # _target_: segmentation_models_pytorch.losses.FocalLoss
  # mode: binary

  # IoU Loss for binary-class or multi-label or multi-class
  # _target_: segmentation_models_pytorch.losses.JaccardLoss
  # mode: binary
  # smooth: 0.1
