_target_: src.models.unet.UNetModule

use_ema: true

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.005
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ExponentialLR
  _partial_: true
  gamma: 0.95

net:
  _target_: src.models.unet.net.UNet

  in_channels: 1 # the channel count of the input
  out_channels: 1 # the channel count of the output
  base_channels: 64 # the base channel count for the model
  block: Residual # type of blocks for each level
  n_layer_blocks: 1 # number of blocks at each level
  channel_multipliers: [1, 2, 4] # the multiplicative factors for number of channels for each level
  drop_rate: 0 # drop out layer


loss: "ce"
weight_loss: [1, 50]
