_target_: src.models.unet.UNet

img_channels: 1 # the channel count of the image
channels: 64 # the base channel count for the model
block: Residual # type of blocks for each level
n_layer_blocks: 1 # number of blocks at each level
channel_multipliers: [1, 2, 4, 4] # the multiplicative factors for number of channels for each level
attention: SelfAttention # type of attentions for each level
attention_levels: [1, 2] # the levels at which attention should be performed
n_attention_heads: 4 # the number of attention heads
n_attention_layers: 1 # the number of attention layers
n_classes: null # the number class
d_cond_image: null # the number of dimension of image condition. Defaults to None.
d_cond_text: null # the number of dimension of text condition. Defaults to None.
drop_rate: 0 # drop out layer
