defaults:
  - sampler: ddim

_target_: src.models.diffusion.net.DiffusionModel

denoise_net:
  _target_: src.models.unet.net.UNetAttention

  in_channels: 1 # the channel count of the input
  out_channels: 1 # the channel count of the output
  base_channels: 64 # the base channel count for the model
  block: Residual # type of blocks for each level
  n_layer_blocks: 1 # number of blocks at each level
  channel_multipliers: [1, 2, 4] # the multiplicative factors for number of channels for each level
  attention: SelfAttention # type of attentions for each level
  attention_levels: [1, 2] # the levels at which attention should be performed
  n_attention_heads: 4 # the number of attention heads
  n_attention_layers: 1 # the number of attention layers
  d_cond_image: null # the number of dimension of image condition
  d_cond_text: null # the number of dimension of text condition
  drop_rate: 0 # drop out layer

n_train_steps: 1000 # the number of diffusion step
img_dims:
  - ${model.net.denoise_net.in_channels}
  - ${data.image_size}
  - ${data.image_size}

gif_frequency: 20
classifier_free: false
