_target_: models.diffusion.DiffusionModel

t_range: 1000 # number of diffusion step
img_dims: [3, 32, 32] # resolution of image
channels: 64 # the base channel count for the model
backbone: "Base" # name of blocks for each level
n_layer_blocks: 1 # number of blocks at each level
channel_multipliers: [1, 2, 4, 4] # the multiplicative factors for number of channels for each level
attention: "Base" # name of attentions
attention_levels: [1, 2] # the levels at which attention should be performed
n_attention_heads: 4 # is the number of attention heads
n_attention_layers: 1 # is the number of attention layers
