_target_: src.models.LatentDiffusionModule

defaults:
  - net: diffusion.yaml
  - autoencoder: autoencoder.yaml
  - _self_

# net:
#   denoise_model:

# autoencoder:
#   encoder: null

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0002
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10
