# https://www.tensorflow.org/tensorboard/

tensorboard:
  _target_: pytorch_lightning.loggers.TensorBoardLogger
  save_dir: "${paths.output_dir}/logs/tensorboard"
  name: "MNIST"
  log_graph: False
  default_hp_metric: True
  prefix: ""
