defaults:
  - model_checkpoint.yaml
  - model_summary.yaml
  - rich_progress_bar.yaml
  - lr_monitor.yaml
  - gen_sample.yaml
  - metrics.yaml
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "val/mae"
  mode: "min"
  save_last: True
  auto_insert_metric_name: False

model_summary:
  max_depth: -1

metrics:
  _target_: src.utils.callbacks.Metrics
  n_ensemble: 1
  fid:
    _target_: torchmetrics.image.FrechetInceptionDistance
    feature: 2048
    normalize: True
  IS:
    _target_: torchmetrics.image.InceptionScore
    feature: 2048
    normalize: True
