defaults:
  - model_checkpoint.yaml
  - early_stopping.yaml
  - model_summary.yaml
  - rich_progress_bar.yaml
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "val/mae"
  mode: "min"
  save_last: True
  auto_insert_metric_name: False

early_stopping:
  monitor: "val/mae"
  patience: 100
  mode: "min"

model_summary:
  max_depth: -1

diff:
  _target_: src.utils.callbacks.DiffusionCallback
  gen_shape: [10, 10]
  gen_type: ddim
  mean: ${data.transform_val.transforms[1].mean}
  std: ${data.transform_val.transforms[1].std}
  callbacks:
    - sample
    - fid
    - is
  feature: 64