metrics:
  _target_: src.utils.callbacks.Metrics
  ssim:
    _target_: torchmetrics.image.StructuralSimilarityIndexMeasure
    data_range: 2.0
  psnr:
    _target_: torchmetrics.image.PeakSignalNoiseRatio
    data_range: 2.0
  fid:
    _target_: torchmetrics.image.FrechetInceptionDistance
    feature: 2048
    normalize: True
  IS:
    _target_: torchmetrics.image.InceptionScore
    feature: 2048
    normalize: True
