metrics:
  _target_: src.utils.callbacks.Metrics
  ssim: null
  psnr: null
  fid: null
  IS: null
  dice: null
  mean: ${data.transform_val.transforms[1].mean}
  std: ${data.transform_val.transforms[1].std}
