metrics:
  _target_: src.utils.callbacks.Metrics
  metric_list:
    - binary-dice
    - binary-iou
    - ssim
    - psnr
    - fid
    - is
    - image_variance
    - boundary_variance

  mean: ${data.transform_val.transforms[1].mean}
  std: ${data.transform_val.transforms[1].std}
  n_ensemble: null
