defaults:
  - model_checkpoint.yaml
  - model_summary.yaml
  - rich_progress_bar.yaml
  - lr_monitor.yaml
  - gen_sample.yaml
  - metrics.yaml
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "val/dice"
  mode: "max"
  save_last: True
  auto_insert_metric_name: False

model_summary:
  max_depth: -1

metrics:
  _target_: src.utils.callbacks.Metrics
  dice:
    _target_: torchmetrics.Dice
    average: micro
    ignore_index: 0
  iou:
    _target_: torchmetrics.JaccardIndex
    average: micro
    task: binary
    # ignore_index: 0 # error from torchmetrics
