defaults:
  - model_checkpoint.yaml
  - model_summary.yaml
  - rich_progress_bar.yaml
  - lr_monitor.yaml
  - gen_sample.yaml
  - metrics.yaml
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "val/mae"
  mode: "min"
  save_last: True
  auto_insert_metric_name: False

model_summary:
  max_depth: -1

metrics:
  _target_: src.utils.callbacks.Metrics
  n_ensemble: 5
  dice:
    _target_: torchmetrics.Dice
    threshold: 0.5
    average: micro
  iou:
    _target_: torchmetrics.JaccardIndex
    threshold: 0.5
    average: micro
    task: binary
  mean_variance:
    _target_: torchmetrics.MeanMetric
  mean_boundary_variance:
    _target_: torchmetrics.MeanMetric
  boundary_threshold: 0.05

gen_sample:
  n_ensemble: 5
