defaults:
  - data: cifar10.yaml
  - model: diffusion.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml
  - _self_

task_name: inference
device: cuda
checkpoint: last
gen_type: ddpm
gen_shape: [10, 10]
checkpoint_dir: "${paths.log_dir}/train/runs/2023-03-25_16-20-52/checkpoints/"
mean: ${data.transform_train.transforms[-2].mean}
std: ${data.transform_train.transforms[-2].std}
