defaults:
  - data: fashion.yaml
  - paths: default.yaml
  - hydra: default.yaml
  - _self_

task_name: inference
device: cuda
grid_shape: [10, 10]
ckpt_path: null # ${paths.log_dir}/.../.ckpt
mean: ${data.transform_val.transforms[1].mean}
std: ${data.transform_val.transforms[1].std}
