defaults:
  - callbacks: default.yaml
  - datamodule: diffusion_datamodule.yaml
  - logger: default.yaml
  - model: diffusion.yaml
  - paths: default.yaml
  - trainer: gpu.yaml
  - _self_

callbacks:
  early_stopping: null
  model_summary: null
  rich_progress_bar: null

datamodule:
  name: "fashion"
  img_dims: [1, 32, 32]
  batch_size: 1
  augmentation: False

logger:
  comet:
    project_name: "fashion"
    experiment_name: "ResnetBlock-BaseAttention"
  tensorboard:
    name: "fashion"

model:
  img_dims: ${datamodule.img_dims}
  backbone: "Resnet" # name of blocks for each level
  n_layer_blocks: 2 # number of blocks at each level
  attention: "Base" # name of attentions
  attention_levels: [0, 1, 2] # the levels at which attention should be performed
  n_attention_heads: 4 # is the number of attention heads
  n_attention_layers: 2 # is the number of attention layers

trainer:
  max_epochs: 15

load_model: False
index_checkpoint: -1
checkpoint_dir: "${paths.root_dir}/outputs/2022-12-30/15-49-49/checkpoints/"
