_target_: src.models.unet.net.UNetPlusPlus

in_channels: 1
out_channels: 2
number_unet: 4
base_channels: 64
conv_layer: Conv2d
norm_layer: InstanceNorm2d
activate_layer: LeakyReLU
transpconv_layer: ConvTranspose2d
conv_kwargs:
  kernel_size: 3
  padding: 1
norm_kwargs:
  eps: 1e-05
  affine: true
activate_kwargs:
  negative_slope: 0.01
  inplace: true
transpconv_kwargs:
  stride: 2
  kernel_size: 2
  bias: false