_target_: src.models.unet.net.UNetAttention

in_channels: 1 # the channel count of the input
out_channels: 1 # the channel count of the output
base_channels: 64 # the base channel count for the model
block: Residual # type of blocks for each level
n_layer_blocks: 1 # number of blocks at each level
channel_multipliers: [1, 2, 4] # the multiplicative factors for number of channels for each level
drop_rate: 0 # drop out layer
