_target_: src.models.components.autoencoder.AutoEncoder

defaults:
  - encoder.yaml
  - decoder.yaml
  - _self_

decoder:
  out_channels: ${model.net.encoder.in_channels}

emb_channels: 4
z_channels: 4
