encoder:
  _target_: src.models.components.Encoder
  in_channels: 1
  channels: 64
  z_channels: 4
  backbone: ResNet
  n_layer_blocks: 1
  channel_multipliers: [1, 2, 4, 4]
  attention: SelfAttention
  attention_levels: [1, 2]
  n_attention_heads: 4
  n_attention_layers: 1
